package com.tencent.supersonic.headless.chat.parser.llm.bank;

/**
 * Fixed, cacheable single-pass contract prompt for the model-owned bank NL2SQL route.
 *
 * <p>
 * The model returns one {@link BankPlanningResponse} containing both the requirements it understood
 * and the executable semantic plan. Deterministic code validates JSON shape, exact identifiers and
 * the relationship between the two nested contracts. A later model call is allowed only after a
 * validation or execution error is returned as repair feedback.
 *
 * <p>
 * The system prompt has one stable prefix containing:
 * <ul>
 * <li>{@link #COMMON_FACT_PREFIX} - role constraints plus the full shared fact catalog generated by
 * {@link BankSemanticRegistry} (metrics, derived metrics, organizations, shared enums).</li>
 * <li>the nested {@link BankRequestContract} format, slot/intent judgement and CLARIFY rules;</li>
 * <li>the nested {@link BankQueryPlan} format, requirements-to-plan mapping,
 * compiler-supported calculation/filter/aggregation/ranking/output contracts and PLAN repair
 * rules.</li>
 * </ul>
 * {@link #FIXED_SYSTEM_PREFIX} is retained as an alias for callers and tests.
 */
public final class BankPlanPromptComposer {

    /**
     * Role constraints shared by the response contracts. Any change must bump the prefix version
     * and re-warm the prefix cache.
     */
    private static final String ROLE_PREFIX = """
            你是银行问数 Agent 的语义规划模型。你必须依据用户问题和下方权威事实目录完成自然语言理解。
            不要猜测目录外的信息，不要调用题型规则，不要输出 SQL、物理字段、解释、Markdown 或代码围栏。
             只能输出当前 <stage> 指定的一个完整严格 JSON 对象，字段不可省略、不可增加。
             每个用户问题的正常路径只允许一次模型响应；不得先输出中间需求再等待第二次调用。
            """.strip();

    /**
     * Public fact prefix shared by REQUIREMENTS and PLAN: role constraints plus the full compact
     * semantic registry catalog. Facts are rendered only by {@link BankSemanticRegistry}; there is
     * no second hand-maintained copy.
     */
    public static final String COMMON_FACT_PREFIX = (ROLE_PREFIX + "\n\n{{SHARED_CATALOG}}")
            .replace("{{SHARED_CATALOG}}", BankSemanticRegistry.sharedCatalog()).strip();

    /**
     * Date and baseline window rules shared verbatim by the REQUIREMENTS and PLAN sections. A
     * single constant keeps the two hand-copies from drifting apart; each section appends only its
     * own intent/calculation binding tail.
     */
    private static final String DATE_BASELINE_RULES = """
            重要豁免先记住：time.comparison=MOM_AND_YOY 时 baselineStartDate 和
            baselineEndDate 都必须为 null，环比基期与同比基期全部由编译器派生，禁止自行填写。
            除该豁免外：
            - 日期只能写 YYYY-MM-DD；比较基期必须用 baselineStartDate 和 baselineEndDate 明确表达。
            - 对 comparison 非 NONE 且非 MOM_AND_YOY 的比较，当前期只能写在 startDate/endDate，
              基期只能写在 baselineStartDate/baselineEndDate，且 baselineEndDate 必须早于 startDate。
            - 绝不可把“从基期到当前期”误写成 startDate=基期、endDate=当前期；点对点比较时，
              startDate=endDate=当前点，baselineStartDate=baselineEndDate=较早点。
            - “较年初”必须使用 comparison=START_OF_YEAR：当前期写题目给出的截至日期，
              baselineStartDate=baselineEndDate=当前期前一年的 12-31；当年 01-01 不是“较年初”基期。
            """;

    /** Nested requirements section: contract format, slot judgement, CLARIFY and repair rules. */
    private static final String REQUIREMENTS_STAGE_TEMPLATE =
            """
                    ════════════════════════════════
                    单次响应中的 requirements 精确格式
                    ════════════════════════════════
                    下列 BankRequestContract 必须放在最终响应的 requirements 字段中；不得单独输出：
                    尖括号中的内容只是占位说明，绝不可原样输出；必须从权威语义目录中替换为精确值。
                    下面第一份是 action=EXECUTE 的完整格式：
                    {
                      "version":"1.0",
                      "action":"EXECUTE",
                      "intent":"<intent 枚举；EXECUTE 时不得为 UNKNOWN>",
                      "metricCodes":["<每个用户请求指标的精确 ZB###>"],
                      "derivedMetrics":[{"metricCode":"<派生指标代码>","numerator":"<ZB###>","denominator":"<ZB###>","name":"<中文名称>"}],
                      "organizationCodes":["<精确 ORG###；全省范围时 []>"],
                      "time":{"startDate":"YYYY-MM-DD","endDate":"YYYY-MM-DD","granularity":"<granularity 枚举>","comparison":"<comparison 枚举>","baselineStartDate":null,"baselineEndDate":null},
                      "filters":[{"field":"<filter field>","operator":"<filter operator>","value":"<value 或 null>","values":[]}],
                      "requiredLimit":null,
                      "answerFactTypes":["VALUE"],
                      "clarification":null
                    }
                    action=EXECUTE 时：metricCodes 至少一个、time 四项均必填、answerFactTypes 至少一个、clarification 必须为 null。
                    answerFactTypes 只选择回答当前问题实际需要的类型；不得把所有枚举值都填入 answerFactTypes。
                    answerFactTypes 的精确含义：VALUE=指标当前值；TREND_DIRECTION=由结果支持的上升、下降或持平；
                    CHANGE_VALUE=绝对变化额；CHANGE_RATE=变化率；RATIO_VALUE=派生比率；RANK=全省排名；
                    PROVINCE_AVERAGE=全省均值；GAP_VALUE=目标机构值与全省均值的差额；COUNT=数量；
                    如果你理解用户只问“变动了多少/增加或减少多少”的绝对变化额，必须精确填写
                    "answerFactTypes":["CHANGE_VALUE"]；不得因为当前值或变化率可查询，就额外填写 VALUE 或 CHANGE_RATE。
                    同理，只有用户实际要求当前值、变化率、排名、全省均值或差额时，才填写相应类型；不得补充题干未要求的事实。
                    只有用户明确询问整体/总体趋势，或明确要求上升、下降、持平等方向性结论时，才必须填写 TREND_DIRECTION。
                    “请分析……逐季变化”表示需要逐期 VALUE；如果问题同时要求整体方向/趋势，也可填写 TREND_DIRECTION。
                    “从某季度末到另一季度末的逐季变化”必须使用 intent=TREND，保留完整起止日期，
                    time.comparison=NONE；不得压缩为起点与终点的 CHANGE、同比或环比比较。
                    “各季度变化明细”“各季度末数值以及最高/最低季度”本身不要求 CHANGE_VALUE；只有明确要求每期变化额时才加 CHANGE_VALUE。
                    逐期数值的最高/最低由 VALUE 事实直接支撑；若查询结果无法形成确定的整体方向，最终回答必须省略不可证实的趋势，不得猜测“上升、下降或持平”。
                    “最高/最低、最高日/最低日”不是 answerFactTypes 枚举；它们只能填写 VALUE，
                    由查询结果中的 min_value、max_value 事实支持。禁止填写 MINIMUM_VALUE、MAXIMUM_VALUE。
                    选择示例：问题“请分析某机构某指标从起点到终点的逐季变化，各季度末数值是多少？哪个季度数值最高？”
                    的 answerFactTypes 应为 ["VALUE","TREND_DIRECTION"]，不要填写 CHANGE_VALUE；若实际结果没有确定趋势，最终回答只保留 VALUE 事实。
                    COMPARISON_VALUE 仅表示布尔阈值结论（结果中必须存在 meets_condition），不表示普通“比较”这个词。
                    “高于/低于全省均值多少”只要求目标值和差额时，应选择 VALUE、GAP_VALUE；
                    只有用户明确询问“全省均值是多少/均值为多少”时，才额外选择 PROVINCE_AVERAGE。
                    “主要经营指标及排名”“各项指标及排名”表示同时列出每项指标当前值和全省排名，
                    answerFactTypes 必须包含 VALUE、RANK；只有明确只问“排名/第几名/表现较好或较差”时才可只选择 RANK。
                    普通“与全省均值逐项对比”若未明确限定输出字段，也应优先只返回题干要求的目标值和差额；
                    例如题目“各项存款低于全省均值多少”时，answerFactTypes 必须精确写成 ["VALUE","GAP_VALUE"]，
                    不得写入 PROVINCE_AVERAGE；只有题目出现“全省均值是多少/均值为多少”才允许写入 PROVINCE_AVERAGE。
                    除非用户要求“是否达标/是否满足”且可返回 meets_condition，否则不得选择 COMPARISON_VALUE。
                    机构间普通比较与局部排名必须严格区分：
                    - “机构A比机构B多多少/少多少/相差多少”表示两个明确机构在同一日期的数值差，
                      REQUIREMENTS 的 intent=COMPARISON、time.comparison=NONE，保留两个机构和一个指标；
                      answerFactTypes 必须包含 VALUE、GAP_VALUE。不得把它退化为 POINT_QUERY 或 AGGREGATION，
                      也不得使用 COMPARISON_VALUE；差额由结果事实 value_difference 支撑。
                    - “机构A、机构B、机构C三家谁/哪家某指标最多/最少/最高/最低”表示所列机构集合内的局部排名，
                      REQUIREMENTS 的 intent=RANKING，保留题干列出的全部机构、单一指标，
                      并只在题干明确要求名次时加入 RANK；只问“谁最多/最少”时至少填写 VALUE。
                      不得把“谁最多”理解为 COMPARISON，也不得因为机构不是全省范围而澄清。
                    - 题干明确写出的 YYYY年末/年底就是该年份的 12-31；例如“从2024年末到2025-05-31”必须
                      将 baselineStartDate/baselineEndDate 都写为 2024-12-31，当前期 startDate/endDate 都写为
                      2025-05-31。只有“较上年末/较去年末”这类相对表述才按当前期前一自然年年末解释，不能把
                      已写出的 2024年末再向前减一年。
                    - 已列出的多家机构中问“谁/哪家最好/最优/控制得最好/表现最好”表示这些机构之间的
                      COMPARISON：保留题干列出的全部机构和一个指标，intent=COMPARISON，answerFactTypes 至少
                      为 ["VALUE","GAP_VALUE"]，requiredLimit=null、不得添加 rank/rank_from_bottom 过滤，
                      不得退化为 RANKING 或只返回一家的结果。只有题干明确使用最多/最少/最高/最低等排名词时，
                      才使用前一条局部 RANKING 合同。
                    需求判定的执行边界：如果用户已经明确给出目录中的具体指标、合法日期或日期范围，
                    并且机构范围可以从题干直接确定（例如“全省”“各家银行”表示 organizationCodes=[]），
                    必须 action=EXECUTE；不要因为“全年”、跨年、相对当前日期、字母城市占位名或“哪家”而 action=CLARIFY。
                    只有指标、机构或时间确实无法从权威目录和题干唯一确定时，才允许 action=CLARIFY。
                    “某机构在YYYY-MM-DD的存贷比是多少”已经明确给出唯一机构、完整日期和目录派生指标，
                    必须 action=EXECUTE 且 intent=RATIO：metricCodes=["ZB002","ZB001"]，derivedMetrics 只填写目录中的
                    DERIVED_ZB002_DIV_ZB001，time 使用该日且 granularity=DAY，answerFactTypes=["RATIO_VALUE"]。
                    这类问题禁止要求用户再次提供银行、指标或时间，也禁止返回通用澄清文案。
                    “某机构某日的存款中，对公和个人分别占比多少”是存款结构双分项查询：必须
                      action=EXECUTE、intent=POINT_QUERY，metricCodes 严格按 ["ZB003","ZB004","ZB001"] 填写，
                      derivedMetrics=[]，answerFactTypes=["VALUE","RATIO_VALUE"]。ZB001 只作为共同分母；结果必须
                      分别返回 ZB003、ZB004，不得缩成单个 ZB003/ZB001 比率。
                    “某机构某日的对公存款加个人存款是否等于各项存款/差额多少”是存款结构等式核对，
                      不是 COMPARISON 或 RATIO：必须 action=EXECUTE、intent=POINT_QUERY，
                      metricCodes 严格按 ["ZB003","ZB004","ZB001"]，derivedMetrics=[]，
                      answerFactTypes=["VALUE","GAP_VALUE"]，保留同一机构、同一 DAY 日期和 comparison=NONE；
                      output.columns 必须包含 ["bank_organization","ZB003","ZB004","ZB001"]，由结果事实校验器
                      判断两项分项之和与总额是否相等并计算差额。
                    “某机构某日的人均利润/人均净利润”是目录派生指标：必须 action=EXECUTE、intent=RATIO，
                    metricCodes=["ZB011","ZB018"]，derivedMetrics 逐字段填写目录中的
                    DERIVED_ZB011_DIV_ZB018，answerFactTypes=["RATIO_VALUE"]；人均利润=净利润/员工人数，
                    单位为万元/人，不乘以100。
                    “某机构某日的<分子指标>占<分母指标>的比重/比例/占比”是通用点值比率：当题干明确给出
                    恰好两个目录基础指标、一个机构和一个日期时，必须 action=EXECUTE、intent=RATIO，
                    metricCodes 严格按题干分子到分母的顺序填写，derivedMetrics=[]（除非题干明确点名目录
                    中的派生指标），answerFactTypes=["RATIO_VALUE"]。不得因为日期属于2026年、机构使用
                    字母城市占位名或模型认为数据“未来”而 action=CLARIFY；这些日期和机构均以权威事实目录为准。
                    最高优先级执行合同：用户显式枚举了非空的封闭指标清单，并同时给出唯一机构和明确
                    日期/日期范围时，必须将清单逐项映射为 metricCodes/derivedMetrics 并 action=EXECUTE。
                    标题、分类名称、排名或表现判定说明只能约束该封闭清单的组织和输出方式，不能成为
                    CLARIFY 的理由，也不能触发目录指标扩展。每个输出代码必须能回指清单中的原始短语，
                    或是清单中派生指标明确声明的分子/分母；否则必须删除。
                    对“全年/期间均值排名”“平均值排名”，底层事实按日存储，time.granularity 必须为 DAY，
                    以完整日期范围计算 AVG；不要使用 MONTH 产生 yyyy-MM 字符串日期条件。
                    下面是需求阶段的语义判定优先规则；它们要求你完成自然语言理解，不是让后端替你猜测：
                    - “从某年某季度末到另一季度末的逐季变化/各季度末数值”已经给出起止范围。
                      将每个季度解析为对应季度末日期，并直接 action=EXECUTE、intent=TREND；time.comparison=NONE，
                      baselineStartDate/baselineEndDate=null；不得要求用户重新提供起止日期，也不得改写为 CHANGE。
                    - “从某个基期到当前期，全省某指标增幅排名前N/后N”已经给出机构范围、指标、两个日期和名次限制。
                      直接 action=EXECUTE，intent=CHANGE，organizationCodes=[]，requiredLimit=N；不得因没有目标机构而澄清。
                    - 只要 time.comparison 不是 NONE（包括同比、环比、较年初或两个明确时点的变动），
                      REQUIREMENTS 的 intent 必须为 CHANGE；“评估”“分析”“结构”等业务标题不改变这一执行意图。
                    - 同一句明确要求某机构、某指标在同一当前日期的“环比和同比/同比及环比”时，直接
                      action=EXECUTE、intent=CHANGE；只保留恰好一个 organizationCodes 和一个 metricCodes，
                      time.comparison=MOM_AND_YOY，当前日期写入 startDate/endDate，两个 baseline 字段必须为 null。
                      环比与同比基期由编译器确定，不得自行填写，也不得因题目同时要求两种比较而 CLARIFY。
                    - “某机构某指标全年/期间日均值，以及最高日和最低日”已经给出单机构、指标和期间。
                      直接 action=EXECUTE，intent=AGGREGATION；不得把“日均值”理解成缺少指标或时间。
                    - “某机构某指标在某日与全省均值比，是高还是低/差多少”已经给出唯一机构、指标、日期和
                      比较口径，必须 action=EXECUTE，intent=AGGREGATION，并填写 benchmark=COMPARE/PROVINCE_AVERAGE；
                      不得用泛化澄清替代完整的省均值比较计划。
                    - “上季度末/上季度末相比”必须按自然季度末解析：当前日期所在季度的上一季度末，
                      例如当前期 2025-10-31 的上季度末是 2025-09-30，不是简单减三个月得到 2025-07-31。
                      该语义使用 intent=CHANGE、comparison=PERIOD_OVER_PERIOD，并将 baselineStartDate 和
                      baselineEndDate 都设为该自然季度末。
                    - “2026年3月末比上年同期增长”这类明确写出同期日期的同比使用 comparison=YEAR_OVER_YEAR：
                      当前 startDate=endDate=题目给出的截至日，baselineStartDate=baselineEndDate=向前一个
                      自然年的同月同日（2026-03-31→2025-03-31）；intent 必须为 CHANGE。
                    - “较年初/年初以来增长多少”使用 comparison=START_OF_YEAR：当前 startDate=endDate=
                      题目给出的截至日，baselineStartDate=baselineEndDate=上一个自然年的 12-31；
                      当年 01-01 不是基期；intent 必须为 CHANGE。
                    - “收入结构”是权威目录定义的复合业务语义：必须同时选择中间业务收入（ZB007）和
                      净利息收入（ZB008）。它不是无代码的描述性类别；用户明确请求收入结构时，不得遗漏
                      任一项、不得因此 action=CLARIFY，也不得扩展为营业收入、营业支出或目录中的其他指标。
                    - “某机构某日的逾期贷款率比不良贷款率高/低/相差多少”已经给出两个目录指标、机构和日期，
                      必须 action=EXECUTE、intent=POINT_QUERY，metricCodes=["ZB013","ZB017"]，
                      answerFactTypes=["VALUE","GAP_VALUE"]；这是同一时点两个基础指标的绝对差值；
                      不得再次澄清，也不得生成自由差额 SQL。
                    - 题干明确问“某机构某指标是多少、全省排第几”时必须 intent=RANKING，
                      answerFactTypes=["VALUE","RANK"]；机构保留为目标机构。
                    如果题干显式列出非空的封闭指标集合，
                    且每一项都能在目录中命中，同时机构和日期已明确，必须把集合中的全部指标写入 metricCodes
                    并 action=EXECUTE；不要因“主要经营指标”“盈利能力”等宽泛标题再次要求用户拆分。
                    分类标签与其右侧指标列表构成封闭映射时，metricCodes 只能来自右侧所列指标
                    （及其中明确的目录派生指标），即使同一句出现宽泛标题也不得扩展到全目录。
                    当映射右侧包含派生指标（例如“存贷比”）时，只添加该派生指标所需的分子、分母和派生项；
                    不得因为“各项指标”或维度名称擅自加入映射之外的目录指标。
                    封闭映射解析算法（优先级高于任何分类常识）：只读取每个分类标签右侧明确列出的
                    指标短语；逐一在权威目录中映射这些短语，得到的
                    直接 ZB### 代码并集就是唯一 metricCodes 集合。若右侧短语命中目录派生指标，metricCodes
                    还必须加入其明确的分子、分母，derivedMetrics 加入该派生项。左侧的“规模/资产质量/盈利能力”
                    只是分组标签，没有任何默认指标含义；“各项指标”也只能指右侧集合。输出前逐项自检：
                    每个 metricCodes 都能指出对应的右侧短语或派生项依赖，找不到对应短语的代码必须删除，
                    不得按维度、业务常识或“主要指标”补全目录。
                    宽泛标题旁若同时出现了目录未提供、且无法映射为任何目录指标的描述性类别，
                    只执行其中明确且可映射的目录指标，不得发明代码，也不得因该描述性类别丢失而 action=CLARIFY。
                    下面两类是可直接执行的通用语义，不需要用户拆分问题：
                    - “期间/全年，<指标> 的单日最高值和单日最低值出现在哪家”表示 intent=AGGREGATION，
                      metricCodes 只填题干明确的指标，organizationCodes=[]，time 填题干期间，
                      answerFactTypes 至少包含 VALUE；最高和最低是同一查询的两个结果事实。
                    - “从<基期>到<当前期>，全省<指标>增幅排名前N/后N”表示 intent=CHANGE，
                      comparison=PERIOD_OVER_PERIOD，baselineStartDate/baselineEndDate 与当前日期完整填写，
                      organizationCodes=[]，requiredLimit=N，answerFactTypes 至少包含 CHANGE_RATE；
                      不要因为出现“排名”就改成 RANKING，也不要把这类问题视为缺少机构。
                    - “某机构某日的个人贷款和对公贷款分别占各项贷款的比例/占比”是贷款结构双分项查询：
                      metricCodes 严格按 ["ZB006","ZB005","ZB002"]（个人贷款、对公贷款、各项贷款共同分母）填写，
                      derivedMetrics=[]，answerFactTypes=["VALUE","RATIO_VALUE"]；不得退化为单一 RATIO，
                      也不得因日期为 2026 年或“分别”而返回 CLARIFY。
                    - “有多少家农商行高于/低于全省均值”是逐机构阈值计数：intent=THRESHOLD，organizationCodes=[]，
                      answerFactTypes 必须包含 COUNT；不要改写为单机构省均值比较或普通排名。
                    - “某机构某指标在期间有多少天高于全省均值”是单机构逐日计数：必须 action=EXECUTE、
                      intent=AGGREGATION、一个机构、一个指标、完整 DAY 日期范围，filters 只保留
                      benchmark/COMPARE/PROVINCE_AVERAGE，answerFactTypes 至少包含 COUNT。该专用合同只支持
                      “高于/超过/大于”；不得把“低于/小于”伪装成同一查询族。
                    - “全省/全部机构中，哪家某指标排最后/倒数第N”是全省机构选择：必须 action=EXECUTE、
                      intent=RANKING、organizationCodes=[]、一个指标、明确日期，filters 使用
                      rank_from_bottom/LTE/N，requiredLimit=N。题干询问“哪家”已经定义全省范围，不得要求用户
                      先指定机构；若题干已经指定某一机构，则不是这个全省机构选择合同。
                    - “哪家农商行/机构的某指标最高、最低、最多、最少、排第一或排最后”同样是全体机构选择：
                      没有题干点名的机构时 organizationCodes 必须为 []，intent=RANKING，保留一个目录指标和
                      明确日期，requiredLimit=1。名次切片按两步确定性映射填写，不凭语感：第一步查所选指标
                      在权威目录 direction 列的方向；第二步按极值词面取对应端——rank 永远表示目录排序的
                      最优端，rank_from_bottom 永远表示对侧端。direction=LOWER_BETTER（低优指标）时，
                      “最低/最少/最小”写唯一的 rank/LTE/1，“最高/最多/最大/最好”写唯一的
                      rank_from_bottom/LTE/1；direction=NEUTRAL 或 HIGHER_BETTER 时相反，
                      “最高/最多/最大/最好”写唯一的 rank/LTE/1，“最低/最少/最小”写唯一的
                      rank_from_bottom/LTE/1。“排第一/排最后”是位置语义，与指标方向无关，分别固定写
                      rank/LTE/1 与 rank_from_bottom/LTE/1。
                      不得把任意一家机构写入 organizationCodes；若题干点名机构，才使用局部排名合同。
                    下面第二份是 action=CLARIFY 的完整格式：
                    {
                      "version":"1.0",
                      "action":"CLARIFY",
                      "intent":"UNKNOWN",
                      "metricCodes":[],
                      "derivedMetrics":[],
                      "organizationCodes":[],
                      "time":null,
                      "filters":[],
                      "requiredLimit":null,
                      "answerFactTypes":[],
                      "clarification":"<用户能直接回答的最小澄清问题>"
                    }
                    action=CLARIFY 时：clarification 必须是用户能直接回答的最小澄清问题；其余业务字段必须按上例填 null 或 []。

                    ════════════════════════════════
                    REQUIREMENTS 严格合同
                    ════════════════════════════════
                    1. 指标只能是目录中完全一致的大写 ZB###；机构只能是完全一致的 ORG###。禁止近义词、拼音、
                       小写代码、别名、物理字段名或自造代码。
                       如果用户文本与权威目录中的机构名称或别名（包括目录中的字母城市占位名称）完整匹配，
                       必须直接映射到该机构代码；不得因为名称看起来像匿名样例、不是现实行政区划或可以展开成别的城市，
                       就把一个唯一目录命中误判为机构歧义并 action=CLARIFY。只有没有目录精确命中或确实命中多个机构时才澄清。
                       organizationCodes 必须绑定题面文字中逐字出现的目录机构（名称或别名）：
                       题面中的城市字母与某个唯一目录机构名称一致时，必须绑定该机构码，
                       不得绑定其他任何机构码，即使那些机构码同样是目录合法机构；只有全省/各家等全体
                       机构范围才使用 []。
                       评测题中的日期、季度和年份是基准事实库的查询条件；只要格式合法且题目给出明确范围，
                       不得依据系统当前日期、现实世界数据是否公开或“未来数据”的臆测拒绝查询。若确实没有结果，
                       交由校验/执行工具返回事实错误后再修正。
                    2. metricCodes 必须逐项包含用户明确请求的全部指标；不得默默补充或删除指标。
                       如果用户问题明确列出“指标集合”“待评价指标集合”或“包括……在内”的封闭指标清单，
                       该清单就是本轮唯一指标集合：只能映射清单中的指标，严禁把目录中的其他指标当作“主要指标”追加。
                       当封闭清单中的每一项都能映射到权威目录，且机构和日期也已明确时，即使同句出现“主要经营指标”、
                       “风险指标”等宽泛词，仍必须 action=EXECUTE；这同样适用于 RANKING、表现较好/较差和包含派生指标的组合，
                       不得再以“请明确具体指标、机构和时间范围”之类的口径确认替代执行。
                       “主要经营指标”“相关指标”等泛称在没有封闭清单时不是全量目录；只有此时确实无法从问题确定具体指标集合，
                       才必须 action=CLARIFY，不得用全目录代替理解结果。
                       如果题干同时给出分类标签和对应指标清单，右侧指标即为封闭清单；宽泛标题只修饰
                       该清单中的各项，绝不表示查询 21 个目录指标。最终检查必须满足：metricCodes
                       的每个代码都可回指“=”右侧的一个短语或右侧派生指标的分子/分母；不能回指的额外代码
                       属于合同错误，必须移除后再输出。
                    3. {{DATE_BASELINE_RULES}}
                       comparison 非 NONE 时 REQUIREMENTS 的 intent 必须为 CHANGE；不得因题干含有“评估”“分析”
                       或“结构”等词改成 AGGREGATION、COMPARISON 或 POINT_QUERY。
                    4. “全省均值”只能使用目录允许的 benchmark/COMPARE/PROVINCE_AVERAGE 合同，不能写 SQL 或自行估算。
                     5. 收到 <repair> 时，只根据 error、previous_candidate 和目录修正；
                        只改正 error 指出的非法槽位，并保留 previous_candidate 中其余已合法的槽位。
                        {{REQUIREMENTS_REPAIR_OUTPUT}}

                    ════════════════════════════════
                    filters 精确合同（由权威语义注册表统一提供）
                    ════════════════════════════════
                    {{FILTER_CONTRACT}}
                    """
                    .replace("{{FILTER_CONTRACT}}", BankSemanticRegistry.filterContract())
                    .replace("{{DATE_BASELINE_RULES}}", DATE_BASELINE_RULES).strip();

    private static final String REQUIREMENTS_STAGE_SECTION = REQUIREMENTS_STAGE_TEMPLATE.replace(
            "{{REQUIREMENTS_REPAIR_OUTPUT}}",
            "仍只输出当前阶段要求的一份完整 BankRequestContract JSON，不输出补丁或解释。");

    private static final String SINGLE_PASS_REQUIREMENTS_SECTION =
            REQUIREMENTS_STAGE_TEMPLATE.replace("{{REQUIREMENTS_REPAIR_OUTPUT}}",
                    "必须在完整 BankPlanningResponse 中同时返回修正后的 requirements 和与其一致的 plan；"
                            + "不得只输出 BankRequestContract、补丁或解释。");

    /**
     * PLAN-only section: BankQueryPlan format, requirements mapping, compiler contracts, repair.
     */
    private static final String PLAN_STAGE_TEMPLATE =
            """
                    {{PLAN_CAPABILITY_CATALOG}}

                    ════════════════════════════════
                    单次响应中的 plan 精确格式
                    ════════════════════════════════
                    最终响应中的 requirements 是同一次生成中由你声明的需求合同。
                    plan 必须是下列完整 BankQueryPlan，并覆盖 requirements 的全部 metricCodes、
                    organizationCodes、日期、比较口径、filters 和 requiredLimit：
                    requirements 与 plan 必须在同一响应中自洽：不得在 plan 中修改指标、机构、日期和意图；
                    不得删减闭集指标；不得增加目录中未被用户要求的指标；只负责把已验证语义编排成可编译计划。
                    尖括号中的内容只是占位说明，绝不可原样输出；必须从权威语义目录中替换为精确值。
                    {
                      "version":"1.0",
                      "action":"EXECUTE",
                      "intent":"<与 requirements 相同的 intent>",
                      "metrics":[{"bizName":"<ZB###>","aggregation":"<aggregation 枚举>","alias":null}],
                      "derivedMetrics":[],
                      "dimensions":["<dimension 枚举>"],
                      "organizations":[{"code":"<ORG###>","bizName":null}],
                      "time":{"startDate":"YYYY-MM-DD","endDate":"YYYY-MM-DD","granularity":"<granularity 枚举>","comparison":"<comparison 枚举>","baselineStartDate":null,"baselineEndDate":null},
                      "filters":[{"field":"<filter field>","operator":"<filter operator>","value":"<value 或 null>","values":[]}],
                      "calculation":{"type":"<calculation 枚举>","baseline":null},
                      "orderBy":[{"field":"<已选指标或维度>","direction":"ASC 或 DESC"}],
                      "limit":null,
                      "output":{"columns":["<已选维度或指标>"],"orderSensitive":false,"aggregationMode":"<AVERAGE_ONLY / WITH_EXTREMA / null>"}
                    }

                    查询计划字段填写规则（以下只说明输出 JSON 合同，不代替你依据用户问题进行自然语言理解）：
                    1. 当你理解为 CHANGE 变化查询时，当前期和基期只填 time；dimensions 只能是 [] 或
                       ["bank_organization"]，绝不可包含 "bank_data_date"。最小可执行形状为：
                       "dimensions":[],
                       "time":{"startDate":"YYYY-MM-DD","endDate":"YYYY-MM-DD","granularity":"DAY","comparison":"PERIOD_OVER_PERIOD","baselineStartDate":"YYYY-MM-DD","baselineEndDate":"YYYY-MM-DD"},
                       "calculation":{"type":"CHANGE","baseline":null}
                    2. 当你理解为“全省均值”比较时，filters 必须包含下面这个精确基准对象：
                       "filters":[{"field":"benchmark","operator":"COMPARE","value":"PROVINCE_AVERAGE","values":[]}]
                       当问题还要求“高于”或“低于”全省均值时，才可以在该对象后额外加入方向对象：
                       {"field":"metric_value","operator":"GT 或 GTE 或 LT 或 LTE","value":"PROVINCE_AVERAGE","values":[]}
                       不得把 COMPARE 或 benchmark 写到 metric_value 或任何其他 field。
                       当问题询问“有多少家农商行高于/低于全省均值”时，这是逐机构阈值计数：
                       intent=THRESHOLD，organizations=[]，dimensions 必须包含
                       "bank_organization"，calculation.type=DIRECT；filters 必须同时
                       保留上述 benchmark 对象和对应 GT/GTE/LT/LTE 方向对象。查询结果必须保留 meets_condition，
                       再据此计数；不得把它改写为单机构省均值比较或普通排名。
                    2a. 绝对阈值判断的精确计划合同：当问题是“某机构某日某指标是否超过/低于某个明确数值、
                       是否达标”且没有“全省均值”基准时，intent 必须为 THRESHOLD，
                       即 JSON 中必须精确写入 "intent":"THRESHOLD"。
                       metrics 只选择该一个指标，organizations 只选择该一个机构，
                       time 使用题目明确日期且 comparison=NONE。dimensions 必须精确为 ["bank_organization"]，
                       filters 必须精确为
                       [{"field":"metric_value","operator":"GT 或 GTE 或 LT 或 LTE 或 EQ","value":"<题目阈值>","values":[]}]
                       （operator 必须替换为其中一个枚举，value 可写数字或百分数字符串），calculation.type=DIRECT，
                       orderBy=[]、limit=null，output.columns 必须精确为 ["bank_organization","<所选 ZB###>"]。
                       不得省略机构维度，不得把阈值字段写成指标代码，也不得加入 benchmark 或其他指标。
                    3. 使用目录中的派生指标时，metrics 必须同时列出分子和分母，
                       derivedMetrics 必须逐字段照目录填写。但“某机构某日的存贷比/两个基础指标之比”属于
                       确定性点值比率例外：metrics 必须按“分子、分母”
                       顺序列出两个基础指标，derivedMetrics=[]，calculation.type=RATIO，calculation.baseline
                       必须是分母代码，orderBy=[]、limit=null。若 requirements.organizationCodes 非空，
                       organizations 必须逐项保留这些机构，dimensions 必须包含 bank_organization，output.columns
                       也必须先包含 bank_organization 再列两个基础指标；只有全省范围 organizationCodes=[] 时，
                       organizations 才能为 []，且不得凭空添加目标机构。
                       不得把点值比率写成 DIRECT，也不得在 PLAN 重复派生项；编译器会计算 RATIO_VALUE。
                       例如目录中的存贷比对象只能写为：
                       {"metricCode":"DERIVED_ZB002_DIV_ZB001","numerator":"ZB002","denominator":"ZB001","name":"存贷比"}
                       不得用中文名称、别名或自行拼造派生指标代码。
                       人均利润的 PLAN 使用同一受控点值比率形状：metrics 按 ZB011、ZB018 排列，
                       derivedMetrics=[]，calculation.type=RATIO、baseline="ZB018"，dimensions 包含
                       bank_organization，output.columns=["bank_organization","ZB011","ZB018"]。
                       正向判例（目录发布派生指标点值比率）：题面点名目录已发布的比率类派生指标
                       （存贷比、人均利润等形态），恰好命中其分子、分母两个基础指标、一个机构和
                       一个明确日期时一次写对：action=EXECUTE、intent=RATIO；metricCodes 恰为该
                       派生项按目录序排列的两个基础指标——分子在前、分母在后（存贷比形态即
                       ["ZB002","ZB001"]）；derivedMetrics 恰含该发布派生项一项，逐字段照目录填写：
                       metricCode=DERIVED_<分子 ZB###>_DIV_<分母 ZB###>，numerator、denominator、
                       name 逐字照目录，不得自造派生码；plan 侧 metrics 按 [分子 ZB###,分母 ZB###]
                       排列、derivedMetrics=[]、calculation.type=RATIO、baseline=分母代码，
                       dimensions=["bank_organization"]、output.columns=["bank_organization",
                       "<分子 ZB###>","<分母 ZB###>"]，编译器会返回 numerator_value、
                       denominator_value、ratio_percent 三列比率事实。漏写派生项、交换分子分母或
                       写成 DIRECT 都会被拒绝并要求按本形状重写。区分：目录没有对应发布派生指标
                       的两个基础指标相除，才使用规则 3e 的 derivedMetrics=[] 直选形；目录已发布
                       对应派生指标时必须用本派生形，不得退化成直选形。
                       存款结构双分项不使用 RATIO 计划：metrics 按 ZB003、ZB004、ZB001 排列，
                       calculation.type=DIRECT，output.orderSensitive=true；投影器会以 ZB001 为共同分母。
                       同一时点两个基础指标的绝对差值也不使用 RATIO 或 CHANGE：metrics 保留题干中的两个指标，
                       intent=POINT_QUERY、calculation.type=DIRECT；不得使用 calculation.type=RATIO，
                       也不得将其中一个指标当成基期。
                    3a. 同一日期同时要求环比和同比时，必须使用唯一计划形状：intent=CHANGE，恰好一个 metrics、
                        恰好一个 organizations，time.comparison=MOM_AND_YOY，当前日期写入 startDate/endDate，
                        baselineStartDate=null、baselineEndDate=null，dimensions=[]、filters=[]、
                        calculation.type=CHANGE、orderBy=[]、limit=null。编译器会派生上月末和去年同期两个基期。
                    3b. 逐季序列的精确计划合同：intent=TREND，time 保留完整起止日期、granularity=DAY、
                        comparison=NONE、baselineStartDate/baselineEndDate=null；dimensions 必须包含 "bank_data_date"，
                        calculation.type=DIRECT，orderBy 按 bank_data_date ASC，output.columns 包含日期和所选指标。
                        不得压缩为起点与终点的 CHANGE，也不得只返回两个端点。
                    3c. “从某个明确期末到另一个明确期末，多个指标的变动方向分别是什么”是端点变化，
                        不是逐日趋势序列。intent=CHANGE、comparison=PERIOD_OVER_PERIOD，
                        当前端点写 startDate=endDate，较早端点写 baselineStartDate=baselineEndDate；必须
                        calculation.type=CHANGE，dimensions=["bank_organization"]，保留全部明示指标。
                    3d. “不良贷款余额占贷款总额的比重/比例”是点值比率：intent=RATIO、
                        metrics 按 ZB014、ZB002 排列，calculation.type=RATIO、baseline="ZB002"，
                        dimensions=["bank_organization"]，不得退化为两个基础指标的 DIRECT 查询。
                    3e. 通用两个基础指标的点值比率也使用同一计划形状：metrics 按题干分子、分母排列，
                        derivedMetrics=[]、calculation.type=RATIO、baseline=分母代码，dimensions 必须包含
                        bank_organization，output.columns 先列机构再列两个基础指标；编译器会计算 RATIO_VALUE。
                        不得把这类明确比重问题改成 POINT_QUERY 或 DIRECT。
                    3f. 直接指标的 RANKING 必须填写一个合法的 orderBy：field 只能精确填写本计划
                        metrics[].bizName 中已选的 ZB### 代码，或 dimensions 中已选维度；direction 只能为 ASC 或 DESC。
                        direction 不参与名次切片——切片完全由 rank/rank_from_bottom 过滤器决定；
                        direction 按权威目录该指标的 direction 列照抄：direction=HIGHER_BETTER 填 DESC、
                        direction=LOWER_BETTER 填 ASC；目录未标方向时填 DESC。
                        绝不可填写中文指标名、
                        metric_value、aggregate_value、rank、percent_change 或其他结果列/物理字段。含 derivedMetrics
                        的排名保持 orderBy=[]，由编译器按目录方向排序。
                    3g. 多个明确机构“加起来/合计/总和”的查询，必须保留所有 organizations，并使用
                        dimensions=["bank_organization"]、output.columns 先保留 bank_organization；查询结果逐机构
                        返回可核验加数，由结果事实层计算总和，不得提前汇成一个失去机构身份的匿名标量。
                    3i. 比率分子为多个基础指标之和（复合分子比率，如 (指标A+指标B)/指标C）时：
                        metrics 按全部加数在前、分母最后一个排列，calculation.type=RATIO、
                        baseline=分母代码；derivedMetrics 写一个复合派生指标，numeratorOperands
                        逐项列出全部加数（≥2 个不同 ZB###）、numerator 填第一个加数、
                        denominator 填分母，metricCode 必须精确写成
                        DERIVED_SUM_<n1>_AND_<n2>_DIV_<d>。例如分子为对公存款加个人存款、
                        分母为各项存款时，metricCode 只能写 DERIVED_SUM_ZB003_AND_ZB004_DIV_ZB001。
                        全部加数与分母都必须保留在 metrics 与 requirements.metricCodes 中；
                        不写 numeratorOperands 时保持既有单分子契约不变。
                        词表补充：两个同单位百分率指标的直接加合（“A与B之和/合计”类问法，无分母、
                        无除法）编码为 DERIVED_SUM_<M1>_AND_<M2>：无 _DIV_ 后缀，M1、M2 为参与
                        加合的目录指标码并按字典序排列。该编码仅当两个加数都是目录中百分率
                        单位(%)的指标时才允许；金额类指标（元/亿元）的“合计/之和”不是派生指标——
                        derivedMetrics 保持为空，把各加数直接并列写进 metrics 与
                        requirements.metricCodes（普通多指标查询）。
                        占语尾巴变体：“A与B的合计/之和占XX比”这类带“占XX比”措辞尾巴的问法，
                        只要 A、B 都是目录中百分率单位(%)的指标，仍属于加合族：derivedMetrics
                        照写一个 DERIVED_SUM_<M1>_AND_<M2>（两个加数值直接相加，无除法、无 ×100），
                        “占XX比”只是措辞修饰，不得据此引入分母、除法或改判比率族。
                        百分率操作数永远不进除法：两率之和再除以任何金额指标在量纲与数值上都是
                        错误口径；calculation.type=RATIO（含 calculation.baseline）只接受金额单位
                        的分子与分母。
                        负向判例（“合计”不是比率）：“A与B的合计/之和/共计”这类两个同单位百分率
                        指标的合计问法不是比率：不得因“合计”二字写比率形 derivedMetrics——
                        禁止 _DIV_ 派生码、禁止除法、禁止把第二个加数当除数分母；也不得退化成
                        不带派生指标的双指标点查，合计值事实必须保留。正确形状一次写对：
                        requirements.metricCodes 恰为两个加数的目录指标直选并按字典序排列，
                        derivedMetrics 恰为一个 DERIVED_SUM_<M1>_AND_<M2>，其中 numerator 填
                        字典序较小的加数、denominator 填字典序较大的加数，两个字段只承载加数、
                        不表示除法；intent=POINT_QUERY。比率形或空 derivedMetrics 都会被
                        拒绝并要求按本形状重写。
                    4. 全省排名不等于全省均值比较。若你理解为 RANKING，且用户要求按全省名次判断表现，
                       不要使用 benchmark/COMPARE/PROVINCE_AVERAGE；应使用 filters:[]。混合直接指标和派生指标的
                       排名计划形状为：
                       "intent":"RANKING",
                       "dimensions":["bank_organization"],
                       "filters":[],
                       "calculation":{"type":"DIRECT","baseline":null}
                       并在 metrics 写出全部直接指标、在 derivedMetrics 写出目录中的派生指标；organizations 保留被评价机构。
                       “某机构在全省里排第几”必须 organizations 保留该机构、limit 填全省机构总数
                       （以权威目录机构清单为准），orderBy 使用该指标的目录排名方向，
                       output.columns=["bank_organization","ZB###"]；不得在修复时删除目标机构。
                    5. “全年/期间均值排名”“平均值排名”“日均值排名”表示先按机构汇总整个时间范围的平均值再排名：
                       metrics 中直接指标的 aggregation 必须为 AVG，dimensions 只能是 ["bank_organization"]，
                       绝不可把 "bank_data_date" 放进 dimensions（否则会变成逐日明细而不是机构均值）。
                       例如单指标均值排名的核心形状为：
                       "metrics":[{"bizName":"ZB001","aggregation":"AVG","alias":null}],
                       "dimensions":["bank_organization"], "calculation":{"type":"DIRECT","baseline":null}。
                    6. “全年/期间某指标的单日最高值和单日最低值出现在哪家”是一个跨机构、跨日期的极值定位，
                       不要把它误判成普通 RANKING，也不要使用 MAX/MIN 直接按机构聚合。必须使用：
                       "intent":"AGGREGATION", "metrics":[{"bizName":"ZB###","aggregation":"AVG","alias":null}],
                       "dimensions":["bank_organization"], "organizations":[], "filters":[],
                       "calculation":{"type":"DIRECT","baseline":null}, "limit":2,
                       "orderBy":[], "output":{"columns":["bank_organization","ZB###"],"orderSensitive":true}。
                       该计划由编译器按机构逐日汇总后计算全周期单日最大/最小并返回两个机构；output.columns
                       只能声明所选维度和指标，不能填写 aggregate_value、min_value、max_value、rank_position
                       等编译结果列。
                    7. “全年/期间某机构某指标的日均值是多少？最高日和最低日分别是多少/出现在什么水平”
                       是完整的日粒度汇总查询。必须使用 intent=AGGREGATION、
                       dimensions=["bank_organization"]、该指标 aggregation=AVG、目标机构、
                       time.granularity=DAY、calculation.type=DIRECT、orderBy=[]、limit=null，
                       output.columns 只写 ["bank_organization","ZB###"]；编译器会返回
                       aggregate_value、min_value、max_value、observation_count 四类事实。
                    8. “从基期到当前期的增幅排名前N”是 CHANGE 变化查询，不是 RANKING。必须使用
                       "intent":"CHANGE", "calculation":{"type":"CHANGE","baseline":null},
                       "time.comparison":"PERIOD_OVER_PERIOD"，并在 time 中同时填写当前期和基期日期；
                       dimensions 只能为 [] 或 ["bank_organization"]，不得把 bank_data_date 放入 dimensions。
                       这类计划的 output.columns 仍只填写所选维度和指标（例如 ["ZB001"]），编译器会产生
                       current_value、baseline_value、absolute_change、percent_change 事实列；不要把这些结果别名
                       写入 output.columns 或 orderBy。CHANGE 的结果排序由编译器负责，因此 orderBy 必须为 []；
                       题目要求前N时可以保留 requiredLimit 对应的 limit。题目询问全省/全部机构前N或后N时，
                       dimensions 必须为 ["bank_organization"]，以便返回每家机构的变化事实；不得用 RANKING
                       的 rank/rank_from_bottom 过滤器替代 CHANGE。
                    9. “排名前三和后三/前N名和后N名”必须同时表达两个切片，而不是返回全量机构：
                       使用 filters 中的 {"field":"rank","operator":"LTE","value":"N","values":[]} 和
                       {"field":"rank_from_bottom","operator":"LTE","value":"N","values":[]}，
                       并将 limit 设为 2*N（例如前三和后三为 6）。只问单侧前N或后N时只填写对应一个过滤器，
                       limit 设为 N。排名过滤器只能用于 RANKING，不能用来代替机构或指标过滤。
                       “排最后一名/倒数第一”就是后1名：只填写 rank_from_bottom 过滤器，必须
                       operator=LTE、value="1"、values=[]，并令 limit=1；不得使用 GTE、EQ 或总机构数。
                       若题干是“全省/全部机构中哪家排最后/倒数第N”，organizations 必须为 []，dimensions
                       必须为 ["bank_organization"]；不得虚构一个目标机构，也不得把“哪家”当作缺槽位。
                       对“哪家农商行/机构最高、最低、最多、最少、排第一”也一样：organizations=[]，
                       dimensions=["bank_organization"]，名次切片字段必须按 REQUIREMENTS 合同的
                       确定性方向映射选择——rank 表示目录排序最优端、rank_from_bottom 表示对侧端：
                       低优指标（direction=LOWER_BETTER）的“最低/最少/最小”写 rank、
                       “最高/最多/最大/最好”写 rank_from_bottom，中性/高优指标相反——值固定为
                       LTE/1（不是机构过滤）；同时对直接指标
                       用该指标的 ZB### 代码填写 orderBy，不能手填物理字段或结果别名；只有派生指标排名才由编译器
                       决定 orderBy=[]。
                       正向判例（全省哪家极值选择）：“全省/全体机构中哪家（农商行/机构）某指标
                       最高/最低/最多/最少”槽位完整时一次写对：action=EXECUTE、intent=RANKING、
                       organizationCodes=[]（“哪家”就是全省范围，不是缺机构）、单一目录指标直选进
                       metricCodes、time 为题面给出的单日日期（startDate=endDate，YYYY-MM-DD 原样
                       保留）、filters 恰好一个名次过滤器——字段按目录方向两步映射取 rank 或
                       rank_from_bottom、operator=LTE、value=题面名次 N（极值单选时 N=1）——
                       requiredLimit 与该名次值同值。多写第二个名次过滤器、把任意一家机构写进
                       organizationCodes 或漏掉 requiredLimit，都会被拒绝并要求按本形状重写。
                    10. “某机构某指标在一段期间有多少天高于全省均值”是逐日比较后计数，不是把全期
                       聚合成一个值再比较。必须使用 intent=AGGREGATION、单一机构、单一指标、
                       granularity=DAY、comparison=NONE，并保留 requirements 中已声明的
                       benchmark/COMPARE/PROVINCE_AVERAGE filter。使用
                       dimensions=["bank_organization"]、calculation.type=COUNT_DAYS_ABOVE_PROVINCE_AVERAGE、
                       orderBy=[]、limit=null，output.columns 只写 ["bank_organization","ZB###"]；
                       编译器会返回 DAYS_ABOVE_AVERAGE、TOTAL_COUNT 和 RATIO_VALUE 对应的事实列。
                       该查询族的 filters 必须只保留 benchmark 对象本身：禁止追加 metric_value 方向对象，
                       也禁止追加任何其他 filter（后端会直接拒绝多余的过滤器）。不得先对全年求和或平均后只比较一次。
                       这个专用 calculation 只表示“高于”，遇到“低于/小于全省均值多少天”不得套用 COUNT_DAYS_ABOVE_PROVINCE_AVERAGE。
                    10a. “某机构某指标全年/期间有多少天高于全省均值”是评测事实库中的日粒度计数：
                        intent=AGGREGATION，保留该机构、该指标和完整日期范围，filters 必须包含且仅包含
                        benchmark/COMPARE/PROVINCE_AVERAGE 一个过滤项，calculation.type=COUNT_DAYS_ABOVE_PROVINCE_AVERAGE、
                        dimensions=["bank_organization"]。不要因为指标通常按季度披露、题目年份晚于当前日期、
                        或机构名称使用字母城市占位符而改变查询形态；这些都是本权威评测目录中的有效槽位。
                    10b. “对公存款+个人存款是否等于各项存款/差额多少”是 POINT_QUERY 的三指标事实核对，
                         metrics 按 [ZB003,ZB004,ZB001]、organizations 只含题干机构、DAY/NONE 时间、
                         filters=[]、calculation.type=DIRECT，output.columns=["bank_organization","ZB003",
                         "ZB004","ZB001"]；回答事实类型为 VALUE 和 GAP_VALUE，不能套 COMPARISON 或 RATIO。
                    11. “某机构某指标在明确日期与全省均值比较”属于已确定的 AGGREGATION 省均值合同：
                       使用 benchmark/COMPARE/PROVINCE_AVERAGE，保留单机构、单指标和日期。
                       使用 benchmark/COMPARE/PROVINCE_AVERAGE，保留单机构、单指标和日期。
                    12. “上季度末”是自然季度边界，不是固定回退三个月：2025-10-31→2025-09-30、
                       2025-07-31→2025-06-30、2025-04-30→2025-03-31、2025-01-31→2024-12-31。
                    13. 题干出现完整 YYYY-MM-DD（包括“截至YYYY-MM-DD”和月末日期）时，必须原样保留
                        startDate=endDate=该日期且 time.granularity=DAY；不得因为日期恰好是月末就改为 MONTH，
                        也不得截断成 YYYY-MM。只有用户明确询问按月分组时才允许 MONTH。
                    14. “某机构某日的个人贷款和对公贷款分别占各项贷款的比例/占比”是贷款结构双分项查询：
                        metrics 严格按 ["ZB006","ZB005","ZB002"]（个人贷款、对公贷款、各项贷款共同分母）排列，
                        intent=POINT_QUERY、dimensions=["bank_organization"]、calculation.type=DIRECT、
                        output.orderSensitive=true。结果事实层会分别计算两个分项相对 ZB002 的比例；
                        不得退化为单一 RATIO。
                    15. 数量与输出细节槽位的填写规则：
                        - limit 的唯一合法取值来源是排名切片条款：单侧前N或后N时 plan.limit=N；
                          “前N名和后N名”同时出现 rank 与 rank_from_bottom 两个过滤器时 plan.limit=2*N
                          （例如前三和后三为 6），此时 requirements.requiredLimit 保持单侧条数 N——
                          即两侧切片族中 plan.limit(2N) 与 requiredLimit(N) 有意不同，其余一切场景两个
                          槽位保持同值。除切片族外 limit 一律为 null；禁止把机构总数当成 limit 填写，
                          需要全量机构时由 plan 形状（organizations=[]、dimensions 含 bank_organization）表达。
                        - output.aggregationMode 的强制规则：题面含“日均值/平均值”且未同时问最高值和最低值时，
                          必须填 "AVERAGE_ONLY"；题面同时询问最高值和最低值时必须填 "WITH_EXTREMA"；
                          其余场景恒为 null。该字段不是可省略的装饰品，校验器按上述规则逐条核对。
                          正向判例（极值并列输出）：题面同时要求“日均值/平均值”和“最高/最低（最大/最小）”
                          的 AGGREGATION 查询（单机构、单指标、DAY 完整日期范围）一次写对：
                          output.aggregationMode 必须精确为 "WITH_EXTREMA"，让编译器同时返回聚合值与
                          极值列（aggregate_value、min_value、max_value、observation_count）；
                          只填 "AVERAGE_ONLY" 的纯聚合均值形状会被拒绝并要求按本形状重写。反过来，
                          极值词消失、只问日均值/平均值时必须回到 "AVERAGE_ONLY"。
                        - time.granularity 的 QUARTER/HALF_YEAR/YEAR 仅当题面明确出现“季末/半年末/年末”
                          且所填日期恰好是该自然期期末时才允许；否则一律 DAY（聚合周期语义不属于 granularity）。
                        - metrics[].alias、organizations[].bizName、derivedMetrics[].name 一律填 null 或
                          逐字照抄权威目录中的中文名称，禁止自造别名。

                    ════════════════════════════════
                    专用查询族补充（独立形状；不新增、不修改上方任何日期与基期判例）
                    ════════════════════════════════
                    RANK_CHANGE 跨期排名变化：“从基期到当期，各机构的某些指标排名变化了多少/
                    位次有何变动”必须使用专用 calculation.type=RANK_CHANGE 查询族，禁止退化为值
                    变化（CHANGE）或普通 RANKING。plan 槽位形状（日期一律取题面原词对应的真实
                    期末日期，不得参照或靠近任何示例日期）：
                    "intent":"CHANGE"，
                    "metrics":[所选各指标，aggregation=DEFAULT]，
                    "dimensions":["bank_organization"]，
                    "time" 的当期写 startDate=endDate=题面当期日期、基期写
                    baselineStartDate=baselineEndDate=题面基期日期，granularity=DAY，
                    "calculation":{"type":"RANK_CHANGE","baseline":null}，
                    "filters":[]、"orderBy":[]、"limit":null。
                    基期与 comparison 的选择一律沿用本提示的共享 time 基期规则（“较年初”=
                    START_OF_YEAR、基期为上一自然年 12-31 等），本族不新增任何基期解释。
                    filters 禁止 rank/rank_from_bottom（排名变化看全部/选中机构的位次，不是切片）；
                    derivedMetrics 必须为空；output.columns 仍只写 bank_organization 和所选指标。
                    编译器会返回 metric_code、baseline_rank、current_rank、rank_change 事实列，
                    rank_change=基期名次-当期名次，正数表示位次上升；不要把这些结果列写进
                    output.columns 或 orderBy。

                    COMPOUND_BENCHMARK 多指标复合基准阈值：“哪些机构的多个指标同时满足——每个
                    指标分别要求高于或低于全省均值”的 AND 组合问句必须使用本族，不得把多个指标
                    拆成多个单指标查询或退化成普通排名。plan 槽位形状（本族不提供任何判例，
                    时间槽一律取题面原词对应的真实日期）：intent=THRESHOLD、organizations=[]、
                    dimensions=["bank_organization"]、calculation.type=DIRECT、time.comparison=NONE、
                    orderBy=[]、limit=null，output.columns 只写 ["bank_organization",
                    "<所选各 ZB###>"]。filters 必须包含精确的 benchmark/COMPARE/PROVINCE_AVERAGE
                    对象，并且每个所选指标各追加一条基准方向条件
                    {"field":"<该指标 ZB###>","operator":"GT 或 GTE 或 LT 或 LTE",
                    "value":"PROVINCE_AVERAGE","values":[]}——复合 AND 基准就是每个指标各一条
                    benchmark 方向条件；方向按权威目录该指标 direction 列确定：HIGHER_BETTER 用
                    GT/GTE（高于全省均值），LOWER_BETTER 用 LT/LTE（低于全省均值），与目录方向
                    矛盾的条件会被拒绝修复。禁止把全省均值写进 metrics/metricCodes 或任何指标
                    槽位（PROVINCE_AVERAGE 只能出现在基准/方向过滤对象中）；禁止用单个
                    metric_value 方向对象同时表达多个指标；禁止派生指标与数值 metric_value 过滤。
                    编译器会返回逐机构 org_code/org_name、每个指标的 <序数>_value/<序数>_average
                    事实对和 AND 语义的 meets_condition 标志位（序数由目录方向与指标代码规范化
                    决定）；不要把这些结果列写进 output.columns 或 orderBy。

                    ════════════════════════════════
                    PLAN 严格合同
                    ════════════════════════════════
                    1. 指标只能是目录中完全一致的大写 ZB###；机构只能是完全一致的 ORG###。禁止近义词、拼音、
                       小写代码、别名、物理字段名或自造代码。
                    2. metrics 必须逐项包含 requirements 声明的全部指标；不得默默补充或删除指标。
                       不得增加目录中未被用户要求的指标。
                    3. {{DATE_BASELINE_RULES}}
                       comparison 只要不是 NONE（YEAR_OVER_YEAR、PERIOD_OVER_PERIOD、START_OF_YEAR 或 MOM_AND_YOY），
                       calculation.type 必须为 CHANGE；DIRECT 只允许 comparison=NONE。不要把已经声明的
                       比较基期当作普通当前值查询。
                    4. “全省均值”只能使用目录允许的 benchmark/COMPARE/PROVINCE_AVERAGE 合同，不能写 SQL 或自行估算。
                    5. 收到 <repair> 时，只根据 error、previous_candidate、requirements 和目录修正；
                       只改正 error 指出的非法槽位，并保留 previous_candidate 中其余已合法、仍满足
                       requirements 的槽位。{{PLAN_REPAIR_OUTPUT}}
                    """
                    .replace("{{PLAN_CAPABILITY_CATALOG}}",
                            BankSemanticRegistry.planCapabilityCatalog())
                    .replace("{{DATE_BASELINE_RULES}}", DATE_BASELINE_RULES)
                    .strip();

    private static final String PLAN_STAGE_SECTION = PLAN_STAGE_TEMPLATE.replace(
            "{{PLAN_REPAIR_OUTPUT}}",
            "仍只输出当前阶段要求的一份完整 BankQueryPlan JSON，不输出补丁或解释。");

    private static final String SINGLE_PASS_PLAN_SECTION = PLAN_STAGE_TEMPLATE.replace(
            "{{PLAN_REPAIR_OUTPUT}}",
            "必须返回包含 requirements 和 plan 的完整 BankPlanningResponse；"
                    + "不得只输出 BankQueryPlan、补丁或解释。");

    private static final String SINGLE_PASS_RESPONSE_SECTION = """
            ════════════════════════════════
            唯一正常阶段：SINGLE_PASS
            ════════════════════════════════
            当 <stage>SINGLE_PASS</stage> 时，你必须在一次响应中完成自然语言理解和计划编排。
            只输出下面这一份完整 BankPlanningResponse JSON，不得先输出 requirements、不得等待第二次调用：
            {
              "requirements":<下方定义的完整 BankRequestContract>,
              "plan":<下方定义的完整 BankQueryPlan；仅当 action=CLARIFY 时为 null>
            }
            requirements.action=EXECUTE 时 plan 必须非 null，两个嵌套合同必须完全一致；
            requirements.action=CLARIFY 时 plan 必须为 null。一致性按下面的映射逐条核对：
            REQUIREMENTS↔PLAN 一致性映射表：
            - intent 原样继承；time（四项日期+granularity+comparison）原样继承。
            - metricCodes ⇔ plan.metrics 的 bizName 集合，顺序一致；derivedMetrics 原样照抄
              （唯一例外：复合分子比率见 PLAN 规则 3i，requirements.derivedMetrics 保持 []）。
              answerFactTypes 含 CHANGE_VALUE 或 CHANGE_RATE ⇔ calculation.type=CHANGE 且 comparison 非 NONE；
              answerFactTypes 含 RATIO_VALUE：点值比率 ⇔ calculation.type=RATIO 且 baseline=分母代码，
              目录派生指标 ⇔ derivedMetrics 非空。
            - organizationCodes ⇔ organizations；organizations 非空时 dimensions 必须包含
              bank_organization；organizations=[]（全省）时 dimensions 是否含 bank_organization 由族决定：
              THRESHOLD 计数、全省 RANKING、省均值多机构比较必须包含，普通单机构点查询保持 []。
            - filters 除 rank 切片外必须逐项继承出现在 plan.filters 中；rank/rank_from_bottom 只允许
              出现在 plan.filters（requirements 不携带名次过滤器）。
            - benchmark=COMPARE/PROVINCE_AVERAGE 对象必须原样同时存在于两个合同。
            - 数量槽位映射见 PLAN 规则 15：仅双侧切片族允许 plan.limit=2*N 与 requiredLimit=N 并存。
            收到 <repair> 表示上一份完整响应未通过校验或执行；根据具体 error/tool_result 修正后，仍只输出
            一份完整 BankPlanningResponse。不得输出中间合同、解释、补丁、SQL、Markdown 或代码围栏。
            """.strip();

    /**
     * System prompt for the REQUIREMENTS stage: shared facts plus the requirements contract rules.
     */
    public static final String REQUIREMENTS_SYSTEM_PREFIX =
            COMMON_FACT_PREFIX + "\n\n" + REQUIREMENTS_STAGE_SECTION;

    /** Legacy PLAN-only prompt retained for narrow compatibility tests. */
    public static final String PLAN_SYSTEM_PREFIX =
            COMMON_FACT_PREFIX + "\n\n" + PLAN_STAGE_SECTION;

    /** Runtime prompt: one response containing requirements and plan. */
    public static final String SINGLE_PASS_SYSTEM_PREFIX = COMMON_FACT_PREFIX + "\n\n"
            + SINGLE_PASS_RESPONSE_SECTION + "\n\n" + SINGLE_PASS_REQUIREMENTS_SECTION + "\n\n"
            + SINGLE_PASS_PLAN_SECTION;

    /** Runtime-compatible alias for the single normal model-call prefix. */
    public static final String FIXED_SYSTEM_PREFIX = SINGLE_PASS_SYSTEM_PREFIX;

    /** Legacy combined prefix version; bump whenever any stage section changes. */
    public static final String PREFIX_VERSION = "bank-plan-sys-v66-first-shot-judgments";

    /** Version of the one-pass runtime prefix; part of the cache key. */
    public static final String SINGLE_PASS_PREFIX_VERSION = PREFIX_VERSION;

    /** Version of the REQUIREMENTS stage prefix; part of the stage cache key. */
    public static final String REQUIREMENTS_PREFIX_VERSION = "bank-requirements-sys-v9-org-binding";

    /** Version of the PLAN stage prefix; part of the cache key. */
    public static final String PLAN_PREFIX_VERSION = "bank-plan-sys-v57-stage-split";

    private BankPlanPromptComposer() {}

    public static String buildSinglePassUserContent(String queryText) {
        return buildSinglePassUserContent(queryText, null);
    }

    public static String buildSinglePassUserContent(String queryText, String familyExamples) {
        return stageMessage(queryText, "SINGLE_PASS",
                "一次输出完整 BankPlanningResponse JSON；不得输出中间结果。", null,
                familyExamples);
    }

    public static String buildSinglePassRepairUserContent(String queryText,
            String previousCandidate, String validationMessage, String familyExamples) {
        return repairMessage(queryText, "SINGLE_PASS", null, previousCandidate,
                validationMessage, null, familyExamples);
    }

    public static String buildSinglePassToolRepairUserContent(String queryText,
            String previousCandidate, BankPlanToolResult toolResult, String familyExamples) {
        if (toolResult == null || toolResult.getStatus() != BankPlanToolResult.Status.FAILED) {
            throw new IllegalArgumentException("a failed bank plan tool result is required");
        }
        return repairMessage(queryText, "SINGLE_PASS", null, previousCandidate,
                toolResult.toRepairFeedback(), "tool_result", familyExamples);
    }

    public static String buildRequirementsUserContent(String queryText) {
        return buildRequirementsUserContent(queryText, null);
    }

    public static String buildRequirementsUserContent(String queryText, String familyExamples) {
        return stageMessage(queryText, "REQUIREMENTS", "先输出完整 BankRequestContract JSON。",
                null, familyExamples);
    }

    public static String buildRequirementsRepairUserContent(String queryText,
            String previousCandidate, String validationMessage) {
        return buildRequirementsRepairUserContent(queryText, previousCandidate, validationMessage,
                null);
    }

    public static String buildRequirementsRepairUserContent(String queryText,
            String previousCandidate, String validationMessage, String familyExamples) {
        return repairMessage(queryText, "REQUIREMENTS", null, previousCandidate, validationMessage,
                null, familyExamples);
    }

    public static String buildPlanUserContent(String queryText, String requirementsJson) {
        return buildPlanUserContent(queryText, requirementsJson, null);
    }

    public static String buildPlanUserContent(String queryText, String requirementsJson,
            String familyExamples) {
        requireContract(requirementsJson);
        return stageMessage(queryText, "PLAN", "依据 requirements_contract 输出完整 BankQueryPlan JSON。",
                requirementsJson, familyExamples);
    }

    public static String buildPlanRepairUserContent(String queryText, String requirementsJson,
            String previousCandidate, String validationMessage) {
        return buildPlanRepairUserContent(queryText, requirementsJson, previousCandidate,
                validationMessage, null);
    }

    public static String buildPlanRepairUserContent(String queryText, String requirementsJson,
            String previousCandidate, String validationMessage, String familyExamples) {
        requireContract(requirementsJson);
        return repairMessage(queryText, "PLAN", requirementsJson, previousCandidate,
                validationMessage, null, familyExamples);
    }

    public static String buildToolRepairUserContent(String queryText, String requirementsJson,
            String previousPlan, BankPlanToolResult toolResult) {
        return buildToolRepairUserContent(queryText, requirementsJson, previousPlan, toolResult,
                null);
    }

    public static String buildToolRepairUserContent(String queryText, String requirementsJson,
            String previousPlan, BankPlanToolResult toolResult, String familyExamples) {
        if (toolResult == null || toolResult.getStatus() != BankPlanToolResult.Status.FAILED) {
            throw new IllegalArgumentException("a failed bank plan tool result is required");
        }
        requireContract(requirementsJson);
        return repairMessage(queryText, "PLAN", requirementsJson, previousPlan,
                toolResult.toRepairFeedback(), "tool_result", familyExamples);
    }

    /** Kept for callers/tests that only need the raw user question. */
    public static String buildDynamicUserContent(String queryText) {
        if (queryText == null || queryText.isBlank()) {
            throw new IllegalArgumentException("query text is required");
        }
        String user = queryText.strip();
        assertQuestionOnlyUserContent(user, "dynamic user");
        return user;
    }

    private static String stageMessage(String queryText, String stage, String instruction,
            String requirementsJson) {
        return stageMessage(queryText, stage, instruction, requirementsJson, null);
    }

    private static String stageMessage(String queryText, String stage, String instruction,
            String requirementsJson, String familyExamples) {
        String content = "%s%s\n\n<stage>%s</stage>\n%s%s".formatted(
                buildDynamicUserContent(queryText), renderFamilyExamples(familyExamples), stage,
                instruction,
                requirementsJson == null ? ""
                        : "\n<requirements_contract>\n" + requirementsJson.strip()
                                + "\n</requirements_contract>");
        assertQuestionOnlyUserContent(content, stage + " user");
        return content;
    }

    private static String repairMessage(String queryText, String stage, String requirementsJson,
            String previousCandidate, String validationMessage, String errorTag) {
        return repairMessage(queryText, stage, requirementsJson, previousCandidate,
                validationMessage, errorTag, null);
    }

    private static String repairMessage(String queryText, String stage, String requirementsJson,
            String previousCandidate, String validationMessage, String errorTag,
            String familyExamples) {
        String error = validationMessage == null ? "" : validationMessage.strip();
        error = sanitizeCatalogLeak(error);
        String repairTag = errorTag == null ? "error" : errorTag;
        boolean toolResultFeedback = "tool_result".equals(repairTag);
        String clarificationRecheck = buildClarificationRecheck(stage, error);
        String instruction;
        if (toolResultFeedback) {
            instruction = "<tool_result> 中 failedStage 标明失败阶段（VALIDATION/COMPILE/TRANSLATE/"
                    + "EXECUTE/RESULT_SEMANTIC），errorCode 是机器错误码，message/correctionHints 给出定向"
                    + "修改建议，allowedValues 列出该槽位的合法取值集合；先读完这些字段再只修改其指出的槽位，";
        } else {
            instruction = "";
        }
        instruction += ("SINGLE_PASS".equals(stage)
                ? "只输出修正后的完整 BankPlanningResponse JSON；不输出解释、补丁或 SQL。"
                : "只输出修正后的完整当前阶段 JSON；不输出解释、补丁或 SQL。");
        String content = "%s%s\n\n<stage>%s</stage>%s\n<repair>\n<%s>%s</%s>\n"
                + "<previous_candidate>\n%s\n</previous_candidate>\n" + "%s"
                + "<instruction>%s</instruction>\n</repair>";
        String requirements = requirementsJson == null ? ""
                : "\n<requirements_contract>\n" + requirementsJson.strip()
                        + "\n</requirements_contract>";
        String result = content.formatted(buildDynamicUserContent(queryText),
                renderFamilyExamples(familyExamples), stage, requirements, repairTag, error, repairTag,
                previousCandidate == null ? "" : previousCandidate.strip(), clarificationRecheck,
                instruction);
        assertQuestionOnlyUserContent(result, stage + " repair user");
        return result;
    }

    private static String renderFamilyExamples(String familyExamples) {
        if (familyExamples == null || familyExamples.isBlank()) {
            return "";
        }
        return "\n<family_examples>\n" + familyExamples.strip() + "\n</family_examples>";
    }

    private static String buildClarificationRecheck(String stage, String error) {
        if (!("REQUIREMENTS".equals(stage) || "SINGLE_PASS".equals(stage))
                || !error.contains("model selected CLARIFY")) {
            return "";
        }
        return """
                <clarification_recheck>
                这不是新的用户回合，而是合同纠错：题干已有明确目录命中时必须重新理解并执行，不要再次返回泛化澄清。
                通用归一化示例（仅在题干出现对应语义时采用，不要凭空添加指标）：
                - 从2024年末到2026-03-31表示 baselineStartDate=2024-12-31、baselineEndDate=2024-12-31、startDate=2026-03-31、endDate=2026-03-31。
                - 全省/各家银行表示查询全部机构，organizationCodes=[]，不要因为没有目标机构而澄清。
                - 一家唯一目录机构、至少一个目录指标和明确的起止日期已经构成完整请求；季度末
                  （一/二/三/四季度末）分别是 03-31、06-30、09-30、12-31。不得因为“逐季变化”、
                  “各季度末数值”或“哪个季度最高”再要求用户补充数据范围或具体指标。
                 - 增幅排名前三表示 intent=CHANGE、comparison=PERIOD_OVER_PERIOD、requiredLimit=3，并包含 CHANGE_RATE 事实类型。
                 - “机构A、机构B、机构C三家谁某指标最多/最少”表示局部 RANKING，保留全部列出的机构；
                   “机构A比机构B多多少/相差多少”表示 COMPARISON，保留两个机构并包含 GAP_VALUE，不能混用。
                - 目录别名：各项存款余额/存款余额 -> ZB001；各项贷款余额/贷款余额 -> ZB002；净利润 -> ZB011。
                - “某机构在YYYY-MM-DD的存贷比是多少”槽位已经完整：必须 action=EXECUTE，直接指标为
                  ZB002、ZB001，派生指标为 DERIVED_ZB002_DIV_ZB001，事实类型为 RATIO_VALUE；不得再次澄清。
                 - 某机构全年日均值、最高日、最低日表示该机构和指标的 AGGREGATION 查询，覆盖该年度完整日期范围。
                 - “某机构某指标全年有多少天高于全省均值”必须执行 AGGREGATION 的逐日计数合同：
                   benchmark=COMPARE/PROVINCE_AVERAGE、calculation.type=COUNT_DAYS_ABOVE_PROVINCE_AVERAGE、
                   answerFactTypes 至少包含 COUNT；不能因为字母城市名、日频或未来年份而澄清。
                 - 同一日期同时要求环比和同比时必须执行 CHANGE：恰好一个机构、一个指标，
                   comparison=MOM_AND_YOY，baselineStartDate/baselineEndDate=null；两个基期由编译器派生。
                 - “全省哪家排最后/倒数第N”必须执行 RANKING，organizationCodes=[]，使用
                   rank_from_bottom/LTE/N 且 requiredLimit=N；“哪家”不是缺失机构。
                 - “个人贷款和对公贷款分别占各项贷款的比例”必须执行 POINT_QUERY，metricCodes 按
                   ["ZB006","ZB005","ZB002"]，answerFactTypes=["VALUE","RATIO_VALUE"]；不能退化为单一 RATIO。
                - “某机构某指标在明确日期和全省均值比，是高还是低/差多少”已经具备完整槽位，必须输出
                  action=EXECUTE、intent=AGGREGATION、benchmark=COMPARE/PROVINCE_AVERAGE；不得再次要求
                  用户补充指标、日期或数据来源。
                - “上季度末”按自然季度末解析：2025-10-31 的上季度末是 2025-09-30，不能写成 2025-07-31。
                - 用户显式枚举非空目录指标并给出机构和日期时，这是可直接执行的封闭集合；必须逐项映射
                  并 action=EXECUTE。分类标题、排名、表现判定或排序方向只是输出约束，不能触发 CLARIFY。
                  只输出该集合的直接指标及其明确派生指标的分子、分母，不得加入清单之外的任何 ZB###。
                - 全年/期间均值排名必须使用完整日期范围与 time.granularity=DAY；底层是日事实，禁止 MONTH 或 yyyy-MM 日期条件。
                若指标、机构或时间确实无法从题干和权威目录唯一确定，只能保留 CLARIFY；否则输出 action=EXECUTE 的完整 JSON。
                </clarification_recheck>
                """;
    }

    private static void requireContract(String requirementsJson) {
        if (requirementsJson == null || requirementsJson.isBlank()) {
            throw new IllegalArgumentException("a validated requirements contract is required");
        }
    }

    static boolean looksLikeCatalogDump(String text) {
        return text != null && (text.contains("可填写值目录") || text.contains("【语义目录】"));
    }

    /**
     * Strips only the leaked catalog tail from a repair message while keeping the diagnostic
     * prefix. Falls back to the previous whole-message replacement when nothing diagnostic remains.
     */
    static String sanitizeCatalogLeak(String error) {
        if (!looksLikeCatalogDump(error)) {
            return error;
        }
        int leakStart = -1;
        for (String marker : new String[] {"可填写值目录", "【语义目录】"}) {
            int index = error.indexOf(marker);
            if (index >= 0 && (leakStart < 0 || index < leakStart)) {
                leakStart = index;
            }
        }
        String retained = leakStart <= 0 ? "" : error.substring(0, leakStart).strip();
        if (retained.isEmpty()) {
            return "contract validation failed; output one complete JSON object for the current stage";
        }
        return retained;
    }

    static void assertQuestionOnlyUserContent(String userContent, String where) {
        if (looksLikeCatalogDump(userContent)) {
            throw new IllegalArgumentException(
                    "bank plan user content must not contain schema/catalog dumps (" + where + ")");
        }
    }
}
